apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: <your-ecr-uri>:latest
        ports:
        - containerPort: 8081